/**********************************/
/* Table Name: 유튜브 내용 */
/**********************************/
DROP TABLE you CASCADE CONSTRAINTS;
CREATE TABLE you(
      youno                               NUMBER(10)       NOT NULL       PRIMARY KEY,
      ytitle                               VARCHAR2(50)       NOT NULL,
      ytext                               VARCHAR2(1000)       NOT NULL,      
      url                                 VARCHAR2(1000)       NOT NULL,
      rdate                               DATE       NOT NULL,
      cnt                                 NUMBER(30)        NOT NULL,
      categrpno                            NUMBER(10)       NOT NULL,
  FOREIGN KEY (categrpno) REFERENCES categrp (categrpno)
);

COMMENT ON TABLE you is '유튜브 내용';
COMMENT ON COLUMN you.youno is '유튜브 번호';
COMMENT ON COLUMN you.ytitle is '유튜브 제목';
COMMENT ON COLUMN you.ytext is '유튜브 한줄소개';
COMMENT ON COLUMN you.url is '주소';
COMMENT ON COLUMN you.rdate is '날짜';
COMMENT ON COLUMN you.cnt is '조회수';
COMMENT ON COLUMN you.categrpno is '카테고리 그룹 번호';

drop sequence you_seq;
CREATE SEQUENCE you_seq
  START WITH 1               -- 시작 번호
  INCREMENT BY 1           -- 증가값
  MAXVALUE 9999999999  -- 최대값: 9999999 --> NUMBER(7) 대응
  CACHE 2                       -- 2번은 메모리에서만 계산
  NOCYCLE;                     -- 다시 1부터 생성되는 것을 방지


commit;
INSERT INTO you(youno,ytitle,ytext,url,rdate,cnt,categrpno)
VALUES(you_seq.nextval,'죽음의 타바타 운동','유튜브 한줄소개','<iframe width="956" height="538" src="https://www.youtube.com/embed/4EKo44DUvjg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',sysdate,0,4);
INSERT INTO you(youno,ytitle,ytext,url,rdate,cnt,categrpno)
VALUES(you_seq.nextval,'40분 유산소 운동','유튜브 한줄소개','<iframe width="956" height="538" src="https://www.youtube.com/embed/myNjmnvI6x0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',sysdate,0,4);
INSERT INTO you(youno,ytitle,ytext,url,rdate,cnt,categrpno)
VALUES(you_seq.nextval,'크로스핏','유튜브 한줄소개','<iframe width="853" height="480" src="https://www.youtube.com/embed/1lBhiUtKVJc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',sysdate,0,4);
INSERT INTO you(youno,ytitle,ytext,url,rdate,cnt,categrpno)
VALUES(you_seq.nextval,'40분 유산소 운동','유튜브 한줄소개','<iframe width="956" height="538" src="https://www.youtube.com/embed/myNjmnvI6x0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',sysdate,0,4);

SELECT youno, ytitle, ytext, url, rdate, cnt, categrpno
FROM you
ORDER BY youno ASC;
commit;
     YOUNO YTITLE                                             URL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      RDATE           CNT  CATEGRPNO
---------- -------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------- ---------- ----------
         2 죽음의 타바타 운동                                 <iframe width="956" height="538" src="https://www.youtube.com/embed/4EKo44DUvjg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 22/06/03          0          4
         3 40분 유산소 운동                                   <iframe width="956" height="538" src="https://www.youtube.com/embed/myNjmnvI6x0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 22/06/03          0          4

         
SELECT youno, ytitle, url, rdate, cnt, categrpno
FROM you
WHERE categrpno = 4  
ORDER BY youno ASC;
     YOUNO YTITLE                                             URL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      RDATE           CNT  CATEGRPNO
---------- -------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------- ---------- ----------
         2 죽음의 타바타 운동                                 <iframe width="956" height="538" src="https://www.youtube.com/embed/4EKo44DUvjg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 22/06/03          0          4
         3 40분 유산소 운동                                   <iframe width="956" height="538" src="https://www.youtube.com/embed/myNjmnvI6x0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 22/06/03          0          4



-- 수정
UPDATE you
SET categrpno=4, ytitle='죽음의 운동(타바타)'
WHERE youno = 2;

SELECT * FROM you;

commit;

   YOUNO YTITLE                                             URL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      RDATE           CNT  CATEGRPNO
---------- -------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------- ---------- ----------
         2 죽음의 운동(타바타)                                <iframe width="956" height="538" src="https://www.youtube.com/embed/4EKo44DUvjg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 22/06/03          0          4
         3 40분 유산소 운동                                   <iframe width="956" height="538" src="https://www.youtube.com/embed/myNjmnvI6x0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 22/06/03          0          4

커밋 완료.

-- 삭제
DELETE you
WHERE youno = 4;

SELECT * FROM you;

commit;
    YOUNO YTITLE                                             URL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      RDATE           CNT  CATEGRPNO
---------- -------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------- ---------- ----------
         2 죽음의 운동(타바타)                                <iframe width="956" height="538" src="https://www.youtube.com/embed/4EKo44DUvjg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 22/06/03          0          4
         3 40분 유산소 운동                                   <iframe width="956" height="538" src="https://www.youtube.com/embed/myNjmnvI6x0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 22/06/03          0          4

커밋 완료.
